### ISSUE TITLE
Is it possible to specify the output folder for the R results?

### ISSUE THREAD

**Issue by f6v** [liulab-dfci/MAESTRO#115]
The files generated from `R` analysis are being saved to the working directory. Is it possible to specify a dedicated folder, or that needs to be implemented as a feature?

**Comment by crazyhottommy** [comment]
It is not possible now. why do you want that? now the results are organized in certain folder structures.

**Comment by f6v** [comment]
When I run just the R code on the counts directly (without running MAESTRO CLI pipeline), the files get dumped into the working directory. The output just gets mixed with other files.

**Comment by crazyhottommy** [comment]
which function are you using? we can add parameters to specify output folder

**Comment by baigal628** [comment]
Hi,

If you only used the MAESTRO R package, the output will always be written in your current working directory. Output files will have the same prefix which is based on what you assigned to 'project'.

You can either setwd() to a dir you want or use a specific name for the 'project' so that they won't get mixed.

**Comment by f6v** [comment]
Yeah, what I end up doing is moving all the generated files to a dedicated directory based on the `project` prefix after the code is done.
